# Change these first
owner: Tecwizard # Your GitHub organization or username, where this repository lives
repo: TRP-Status # The name of this repository

sites:
  - name: Terra Isles Website
    url: https://www.terraisles.com
  - name: TeamSpeak Server
    url: http://ts3.terraisles.com
  - name: FiveM Server
    url: http://fivem.terraisles.com:32024
  - name: Iceburg Server
    url: http://fivem.terraisles.com/
  - name: Arma Server
    url: http://games1.madzahttr.com:2302

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.terra-isles.com
  # baseUrl: /your-repo-name
  logoUrl: https://i.postimg.cc/FFWZzqZZ/Favicon-1.png
  name: TRP Upptime
  introTitle: "This is **Upptime**. It's the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page is used to monitor the status of the various servers and services Terra Isles Roleplay manages and maintains. The code that makes up this page is entirely open source.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
